name: Release

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v1
      - uses: bubkoo/release-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
