name: Python tests

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on:
  pull_request:
    paths:
      - .github/workflows/tests.yaml
      - "**/*.py"
      - poetry.lock
      - pyproject.toml
      - Dockerfile
  push:
    branches:
      - master

permissions:
  contents: read

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: Run Pytest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}-root
      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry==1.2.1"
      - name: Configure poetry
        run: python -m poetry config virtualenvs.create false
      - name: Lint
        run: python -m poetry run bash scripts/ci/lint.sh
      - name: Test
        run: python -m poetry run bash scripts/ci/test.sh
